"""Ausgangsrevision: Schema zum Zeitpunkt der Einführung von Alembic.

Ältere SQLite-Entwicklungsdatenbanken werden über ``backend.legacy_migrations``
auf diesen Stand gebracht und dann gestempelt (``backend.migrate``).

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-14 05:16:38.677232
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('cultural_diversity_score', sa.Float(), nullable=True),
    sa.Column('special_needs_score', sa.Float(), nullable=True),
    sa.Column('is_resident', sa.Boolean(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('score_calculated_at', sa.DateTime(), nullable=True),
    sa.Column('wbs_status', sa.String(), nullable=True),
    sa.Column('pets_count', sa.Integer(), nullable=True),
    sa.Column('pets_info', sa.String(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('financial_status', sa.String(), nullable=True),
    sa.Column('import_source', sa.String(), nullable=True),
    sa.Column('import_timestamp', sa.DateTime(), nullable=True),
    sa.Column('household_member_count', sa.Integer(), nullable=True),
    sa.Column('apartment_unit', sa.String(), nullable=True),
    sa.Column('vcf_import_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_households_name'), ['name'], unique=False)

    op.create_table('scoring_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('scoring_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_config_key'), ['key'], unique=False)

    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(), nullable=True),
    sa.Column('size_rooms', sa.Integer(), nullable=True),
    sa.Column('funding_type', sa.String(), nullable=True),
    sa.Column('apartment_category', sa.String(), nullable=True),
    sa.Column('is_small', sa.Boolean(), nullable=True),
    sa.Column('area_shares', sa.Float(), nullable=True),
    sa.Column('area_rent', sa.Float(), nullable=True),
    sa.Column('area_utilities', sa.Float(), nullable=True),
    sa.Column('min_occupants', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apartments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apartments_unit_number'), ['unit_number'], unique=True)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('occupation_type', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('cultural_background', sa.String(), nullable=True),
    sa.Column('special_needs', sa.String(), nullable=True),
    sa.Column('member_number', sa.String(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('individual_import_timestamp', sa.DateTime(), nullable=True),
    sa.Column('vcf_import_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_id'), ['id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('wishes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_note', sa.String(), nullable=True),
    sa.Column('special_case', sa.Boolean(), nullable=True),
    sa.Column('special_case_note', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('fulfilled_apartment_id', sa.Integer(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fulfilled_apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_kind'))
        batch_op.drop_index(batch_op.f('ix_applications_id'))
        batch_op.drop_index(batch_op.f('ix_applications_household_id'))

    op.drop_table('applications')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_id'))

    op.drop_table('people')
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apartments_unit_number'))
        batch_op.drop_index(batch_op.f('ix_apartments_id'))

    op.drop_table('apartments')
    with op.batch_alter_table('scoring_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_config_key'))

    op.drop_table('scoring_config')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_name'))
        batch_op.drop_index(batch_op.f('ix_households_id'))

    op.drop_table('households')
    # ### end Alembic commands ###
